package com.example.kennys_dokidoki_wallpaper

import android.content.ContentValues
import android.content.Context
import android.net.Uri
import android.os.Build
import android.os.Environment
import android.provider.MediaStore
import android.util.Log
import android.widget.Toast
import org.json.JSONArray
import org.json.JSONObject
import java.io.File
import java.io.FileInputStream
import java.io.FileOutputStream
import java.io.InputStream
import java.io.OutputStream
import java.text.SimpleDateFormat
import java.util.Date
import java.util.Locale

object BackupManager {
    private const val BACKUP_VERSION = 1

    fun exportBackup(context: Context, outputStream: OutputStream): Boolean {
        return try {
            val root = JSONObject()
            root.put("version", BACKUP_VERSION)
            root.put("timestamp", System.currentTimeMillis())

            // --- TagManager Data ---
            val tagData = JSONObject()
            val categoriesArray = JSONArray()
            TagManager.categories.forEach { cat ->
                val obj = JSONObject()
                obj.put("name", cat.name)
                obj.put("tags", JSONArray(cat.tags))
                cat.parentCategoryName?.let { obj.put("parentCategoryName", it) }
                categoriesArray.put(obj)
            }
            tagData.put("categories", categoriesArray)
            tagData.put("prompts", JSONObject(TagManager.tagPrompts.toMap()))
            tagData.put("remote_ids", JSONObject(TagManager.tagRemoteCardIds.toMap()))
            val impliedObj = JSONObject()
            TagManager.impliedTagsMap.forEach { (tag, set) ->
                impliedObj.put(tag, JSONArray(set.toList()))
            }
            tagData.put("implied_tags", impliedObj)
            root.put("tag_manager", tagData)

            // --- DataManager Data ---
            val dataManagerData = JSONObject()
            val imagesArray = JSONArray()
            DataManager.allImages.forEach { entry ->
                val obj = JSONObject().apply {
                    put("uri", entry.uri.toString())
                    put("isActive", entry.isActive)
                    entry.croppedUri?.let { put("croppedUri", it.toString()) }
                    entry.cropRect?.let {
                        put("crop_left", it.left.toDouble())
                        put("crop_top", it.top.toDouble())
                        put("crop_right", it.right.toDouble())
                        put("crop_bottom", it.bottom.toDouble())
                    }
                    entry.linkedChatId?.let { put("linkedChatId", it) }
                    entry.description?.let { put("description", it) }
                    put("tags", JSONArray(entry.tags.toList()))
                }
                imagesArray.put(obj)
            }
            dataManagerData.put("all_images", imagesArray)
            val setsArray = JSONArray()
            DataManager.imageSetList.forEach { set ->
                val obj = JSONObject().apply {
                    put("name", set.name)
                    put("matchMode", set.matchMode.name)
                    put("isActive", set.isActive)
                    put("isAutoGenerated", set.isAutoGenerated)
                    put("targetTags", JSONArray(set.targetTags.toList()))
                }
                setsArray.put(obj)
            }
            dataManagerData.put("image_sets", setsArray)
            root.put("data_manager", dataManagerData)

            // --- PromptCardManager Data ---
            val promptData = JSONObject()
            val cardsArray = JSONArray()
            PromptCardManager.promptCards.forEach { card ->
                val obj = JSONObject().apply {
                    put("id", card.id)
                    put("label", card.label)
                    put("mainPrompt", card.mainPrompt)
                    put("negativePrompt", card.negativePrompt)
                    put("thumbnailUri", card.thumbnailUri?.toString() ?: "")
                    put("category", card.category)
                    put("appliedTags", JSONArray(card.appliedTags.toList()))
                    put("useIndividualRandomizer", card.useIndividualRandomizer)
                    put("randomizerProbability", card.randomizerProbability)
                }
                cardsArray.put(obj)
            }
            promptData.put("cards", cardsArray)
            promptData.put("category_order", JSONArray(PromptCardManager.categoryOrder))
            promptData.put("random_categories", JSONArray(PromptCardManager.randomEnabledCategories.toList()))
            promptData.put("selection_levels", JSONObject(PromptCardManager.selectionLevels.toMap()))
            promptData.put("collapsed_categories", JSONArray(PromptCardManager.collapsedCategories.toList()))
            promptData.put("randomizer_included_ids", JSONArray(PromptCardManager.randomizerIncludedIds.toList()))
            root.put("prompt_manager", promptData)

            // --- PresetManager Data ---
            val presetData = JSONObject()
            val presetsArray = JSONArray()
            PresetManager.presets.forEach { preset ->
                val obj = JSONObject().apply {
                    put("id", preset.id)
                    put("name", preset.name)
                    put("category", preset.category)
                    put("activePromptStates", JSONObject(preset.activePromptStates.toMap()))
                    put("width", preset.width)
                    put("height", preset.height)
                    put("steps", preset.steps)
                    put("batchCount", preset.batchCount)
                    put("sampler", preset.sampler)
                    put("randomEnabledCategories", JSONArray(preset.randomEnabledCategories.toList()))
                    put("thumbnailUri", preset.thumbnailUri?.toString() ?: "")
                }
                presetsArray.put(obj)
            }
            presetData.put("presets", presetsArray)
            presetData.put("category_order", JSONArray(PresetManager.categoryOrder))
            presetData.put("collapsed_categories", JSONArray(PresetManager.collapsedCategories.toList()))
            root.put("preset_manager", presetData)

            outputStream.use { it.write(root.toString(2).toByteArray()) }
            true
        } catch (e: Exception) {
            Log.e("BackupManager", "Export failed", e)
            false
        }
    }

    fun importBackup(context: Context, inputStream: InputStream): Boolean {
        return try {
            val jsonString = inputStream.bufferedReader().use { it.readText() }
            val root = JSONObject(jsonString)
            
            // --- Restore TagManager ---
            if (root.has("tag_manager")) {
                val tagData = root.getJSONObject("tag_manager")
                TagManager.categories.clear()
                val catsArray = tagData.getJSONArray("categories")
                for (i in 0 until catsArray.length()) {
                    val obj = catsArray.getJSONObject(i)
                    val cat = TagCategory(obj.getString("name"))
                    cat.parentCategoryName = if (obj.has("parentCategoryName")) obj.getString("parentCategoryName") else null
                    val tags = obj.getJSONArray("tags")
                    for (j in 0 until tags.length()) cat.tags.add(tags.getString(j))
                    TagManager.categories.add(cat)
                }
                TagManager.tagPrompts.clear()
                val prompts = tagData.getJSONObject("prompts")
                prompts.keys().forEach { TagManager.tagPrompts[it] = prompts.getString(it) }
                
                TagManager.tagRemoteCardIds.clear()
                val remotes = tagData.getJSONObject("remote_ids")
                remotes.keys().forEach { TagManager.tagRemoteCardIds[it] = remotes.getString(it) }

                TagManager.impliedTagsMap.clear()
                val implied = tagData.getJSONObject("implied_tags")
                implied.keys().forEach { key ->
                    val arr = implied.getJSONArray(key)
                    val set = mutableSetOf<String>()
                    for (i in 0 until arr.length()) set.add(arr.getString(i))
                    TagManager.impliedTagsMap[key] = set
                }
                TagManager.saveTags(context)
            }

            // --- Restore DataManager ---
            if (root.has("data_manager")) {
                val data = root.getJSONObject("data_manager")
                DataManager.allImages.clear()
                val images = data.getJSONArray("all_images")
                for (i in 0 until images.length()) {
                    val obj = images.getJSONObject(i)
                    val entry = ImageEntry(Uri.parse(obj.getString("uri")))
                    entry.isActive = obj.optBoolean("isActive", true)
                    val cUri = obj.optString("croppedUri", "")
                    entry.croppedUri = if (cUri.isNotEmpty()) Uri.parse(cUri) else null
                    if (obj.has("crop_left")) {
                        entry.cropRect = android.graphics.RectF(
                            obj.getDouble("crop_left").toFloat(),
                            obj.getDouble("crop_top").toFloat(),
                            obj.getDouble("crop_right").toFloat(),
                            obj.getDouble("crop_bottom").toFloat()
                        )
                    }
                    entry.linkedChatId = if (obj.has("linkedChatId")) obj.getString("linkedChatId") else null
                    entry.description = if (obj.has("description")) obj.getString("description") else null
                    val tags = obj.getJSONArray("tags")
                    for (j in 0 until tags.length()) entry.tags.add(tags.getString(j))
                    DataManager.allImages.add(entry)
                }
                DataManager.imageSetList.clear()
                val sets = data.getJSONArray("image_sets")
                for (i in 0 until sets.length()) {
                    val obj = sets.getJSONObject(i)
                    val set = ImageSet(obj.getString("name"))
                    set.matchMode = MatchMode.valueOf(obj.getString("matchMode"))
                    set.isActive = obj.optBoolean("isActive", true)
                    set.isAutoGenerated = obj.optBoolean("isAutoGenerated", false)
                    val tags = obj.getJSONArray("targetTags")
                    for (j in 0 until tags.length()) set.targetTags.add(tags.getString(j))
                    DataManager.imageSetList.add(set)
                }
                DataManager.saveData(context)
            }

            // --- Restore PromptCardManager ---
            if (root.has("prompt_manager")) {
                val data = root.getJSONObject("prompt_manager")
                PromptCardManager.promptCards.clear()
                val cards = data.getJSONArray("cards")
                for (i in 0 until cards.length()) {
                    val obj = cards.getJSONObject(i)
                    val card = PromptCard(
                        id = obj.getString("id"),
                        label = obj.getString("label"),
                        mainPrompt = obj.getString("mainPrompt"),
                        negativePrompt = obj.getString("negativePrompt"),
                        thumbnailUri = obj.optString("thumbnailUri", "").let { if (it.isNotEmpty()) Uri.parse(it) else null },
                        category = obj.optString("category", "未分類"),
                        useIndividualRandomizer = obj.optBoolean("useIndividualRandomizer", false),
                        randomizerProbability = obj.optInt("randomizerProbability", 50)
                    )
                    val tags = obj.getJSONArray("appliedTags")
                    for (j in 0 until tags.length()) card.appliedTags.add(tags.getString(j))
                    PromptCardManager.promptCards.add(card)
                }
                PromptCardManager.categoryOrder.clear()
                val catOrder = data.getJSONArray("category_order")
                for (i in 0 until catOrder.length()) PromptCardManager.categoryOrder.add(catOrder.getString(i))
                
                PromptCardManager.randomEnabledCategories.clear()
                val randCats = data.getJSONArray("random_categories")
                for (i in 0 until randCats.length()) PromptCardManager.randomEnabledCategories.add(randCats.getString(i))

                PromptCardManager.selectionLevels.clear()
                val levels = data.getJSONObject("selection_levels")
                levels.keys().forEach { PromptCardManager.selectionLevels[it] = levels.getInt(it) }

                PromptCardManager.collapsedCategories.clear()
                val collapsed = data.getJSONArray("collapsed_categories")
                for (i in 0 until collapsed.length()) PromptCardManager.collapsedCategories.add(collapsed.getString(i))

                PromptCardManager.randomizerIncludedIds.clear()
                val randIds = data.getJSONArray("randomizer_included_ids")
                for (i in 0 until randIds.length()) PromptCardManager.randomizerIncludedIds.add(randIds.getString(i))
                
                PromptCardManager.saveCards(context)
            }

            // --- Restore PresetManager ---
            if (root.has("preset_manager")) {
                val data = root.getJSONObject("preset_manager")
                PresetManager.presets.clear()
                val presets = data.getJSONArray("presets")
                for (i in 0 until presets.length()) {
                    val obj = presets.getJSONObject(i)
                    val statesMap = mutableMapOf<String, Int>()
                    val states = obj.getJSONObject("activePromptStates")
                    states.keys().forEach { statesMap[it] = states.getInt(it) }
                    
                    val randCats = mutableSetOf<String>()
                    val randArr = obj.getJSONArray("randomEnabledCategories")
                    for (j in 0 until randArr.length()) randCats.add(randArr.getString(j))

                    PresetManager.presets.add(Preset(
                        obj.getString("id"),
                        obj.getString("name"),
                        obj.getString("category"),
                        statesMap,
                        obj.getInt("width"),
                        obj.getInt("height"),
                        obj.getInt("steps"),
                        obj.getInt("batchCount"),
                        obj.getString("sampler"),
                        randCats,
                        obj.optString("thumbnailUri", "").let { if (it.isNotEmpty()) Uri.parse(it) else null }
                    ))
                }
                PresetManager.categoryOrder.clear()
                val order = data.getJSONArray("category_order")
                for (i in 0 until order.length()) PresetManager.categoryOrder.add(order.getString(i))
                
                PresetManager.collapsedCategories.clear()
                val collapsed = data.getJSONArray("collapsed_categories")
                for (i in 0 until collapsed.length()) PresetManager.collapsedCategories.add(collapsed.getString(i))
                
                PresetManager.savePresets(context)
            }
            true
        } catch (e: Exception) {
            Log.e("BackupManager", "Import failed", e)
            false
        }
    }

    private const val AUTO_BACKUP_LIMIT = 20
    private var lastKnownTagCount = 0
    private var lastKnownImageCount = 0
    private var isRestoring = false

    /**
     * アプリ起動時に、正常に読み込まれた時点のタグ数と画像数を記憶しておくわ！
     */
    fun initializeLastKnownCounts(context: Context) {
        lastKnownTagCount = TagManager.allTags.size
        lastKnownImageCount = DataManager.allImages.size
        Log.d("BackupManager", "Initialized last known counts: tags=$lastKnownTagCount, images=$lastKnownImageCount")
    }

    /**
     * 保存しようとしているデータが壊れていないか、異常に消去されていないかをチェックするわよ！
     * バグによってすべてのデータが消えるのを水際で防ぐ超重要なディフェンスロジックね☆
     */
    fun validateDataIntegrity(context: Context): Boolean {
        if (isRestoring) return true

        // まだ読み込みが完了していない（または現在読み込み中）の場合は、
        // 不正に整合性チェックを走らせて自動復旧（リストア）を誘発させないように、ここでは検証をスキップ（trueを返す）するわよ！
        if (!DataManager.isLoaded || !TagManager.isLoaded) {
            Log.d("BackupManager", "validateDataIntegrity: Load is not completed yet, skipping verification (returning true to prevent accidental restore).")
            return true
        }

        val currentTagCount = TagManager.allTags.size
        val currentCategoryCount = TagManager.categories.size
        val currentImageCount = DataManager.allImages.size

        // ガード1: カテゴリ数が1以下になっていたら明らかにバグか異常よ！
        if (currentCategoryCount <= 1) {
            Log.e("BackupManager", "Integrity check FAILED: Categories=$currentCategoryCount. Data might be corrupted!")
            return false
        }

        // ガード2: タグや画像の数が、起動時（または前回保存時）に比べて極端に（例えば50%以上）一瞬で減少している場合
        if (lastKnownTagCount > 5 && currentTagCount < (lastKnownTagCount * 0.5)) {
            Log.e("BackupManager", "Integrity check FAILED: Tag count dropped suddenly from $lastKnownTagCount to $currentTagCount!")
            return false
        }
        
        // 画像件数のチェックも同様
        if (lastKnownImageCount > 10 && currentImageCount < (lastKnownImageCount * 0.5)) {
            Log.e("BackupManager", "Integrity check FAILED: Image count dropped suddenly from $lastKnownImageCount to $currentImageCount!")
            return false
        }

        // 正常であれば、最新の件数を更新しておくわ
        lastKnownTagCount = currentTagCount
        lastKnownImageCount = currentImageCount
        return true
    }

    /**
     * 最後の正常な自動バックアップからデータを自動復旧（ロールバック）するわよ！
     */
    fun restoreLatestAutoBackup(context: Context): Boolean {
        if (isRestoring) return false
        isRestoring = true
        
        val backups = getAutoBackupList(context)
        if (backups.isEmpty()) {
            Log.e("BackupManager", "No auto backups available to restore!")
            isRestoring = false
            return false
        }

        val latestBackup = backups.first()
        Log.w("BackupManager", "Attempting automatic restore from ${latestBackup.name}")
        
        return try {
            FileInputStream(latestBackup).use { fis ->
                if (importBackup(context, fis)) {
                    Log.i("BackupManager", "Automatic restore successful from ${latestBackup.name}!")
                    TagManager.loadTags(context)
                    DataManager.loadData(context)
                    
                    lastKnownTagCount = TagManager.allTags.size
                    lastKnownImageCount = DataManager.allImages.size
                    
                    if (context is MainActivity) {
                        context.refreshAllUI()
                        context.runOnUiThread {
                            Toast.makeText(context, "⚠️データ消失バグを検知したため、自動バックアップから安全に復旧したわよ！", Toast.LENGTH_LONG).show()
                        }
                    }
                    true
                } else {
                    false
                }
            }
        } catch (e: Exception) {
            Log.e("BackupManager", "Failed to restore auto backup", e)
            false
        } finally {
            isRestoring = false
        }
    }

    /**
     * ローカルに日時付きで自動バックアップを保存するわよ！
     * 最大20世代まで自動で世代管理して、古いものは削除するから安心ね☆
     */
    fun createAutoBackup(context: Context): File? {
        if (isRestoring) return null
        
        if (!validateDataIntegrity(context)) {
            Log.e("BackupManager", "Auto backup skipped due to data integrity check failure.")
            return null
        }

        val backupDir = File(context.getExternalFilesDir("auto_backups") ?: context.filesDir, "auto_backups")
        if (!backupDir.exists()) {
            backupDir.mkdirs()
        }
        
        val timeStamp = SimpleDateFormat("yyyyMMdd_HHmmss_SSS", Locale.getDefault()).format(Date())
        val file = File(backupDir, "auto_backup_$timeStamp.json")
        
        return try {
            FileOutputStream(file).use { fos ->
                if (exportBackup(context, fos)) {
                    val files = backupDir.listFiles { _, name -> name.startsWith("auto_backup_") && name.endsWith(".json") }
                    if (files != null && files.size > AUTO_BACKUP_LIMIT) {
                        files.sortBy { it.lastModified() }
                        for (i in 0 until (files.size - AUTO_BACKUP_LIMIT)) {
                            files[i].delete()
                        }
                    }
                    file
                } else {
                    file.delete()
                    null
                }
            }
        } catch (e: Exception) {
            Log.e("BackupManager", "Auto backup failed", e)
            null
        }
    }

    /**
     * 自動バックアップに保存されているバックアップファイルのリストを最新順で取得するわ！
     */
    fun getAutoBackupList(context: Context): List<File> {
        val backupDir = File(context.getExternalFilesDir("auto_backups") ?: context.filesDir, "auto_backups")
        if (!backupDir.exists()) return emptyList()
        
        val files = backupDir.listFiles { _, name -> name.startsWith("auto_backup_") && name.endsWith(".json") }
        return files?.sortedByDescending { it.lastModified() } ?: emptyList()
    }
}
