package com.example.kennys_dokidoki_wallpaper

import android.content.Context
import android.graphics.RectF
import android.net.Uri
import android.provider.DocumentsContract
import android.util.Log
import androidx.documentfile.provider.DocumentFile
import org.json.JSONArray
import org.json.JSONObject
import java.io.File
import java.io.FileNotFoundException

object DataManager {
    private const val PREFS_NAME = "wallpaper_prefs"
    private const val KEY_ALL_IMAGES = "all_images"
    private const val KEY_IMAGE_SETS = "image_sets"
    const val KEY_REVISION = "data_revision"

    val allImages = mutableListOf<ImageEntry>()
    val imageSetList = mutableListOf<ImageSet>()

    @Volatile
    var isLoaded = false
        private set

    @Volatile
    private var isLoading = false

    @Synchronized
    fun loadData(context: Context, forceReload: Boolean = false) {
        if (isLoaded && !forceReload) {
            Log.d("DataManager", "loadData: already loaded, skip.")
            return
        }
        if (isLoading) {
            Log.d("DataManager", "loadData: already loading, skip.")
            return
        }
        isLoading = true
        try {
            val prefs = context.getSharedPreferences(PREFS_NAME, Context.MODE_PRIVATE)
            val dataFile = dataFile(context)
            val fileJson = AtomicFiles.readUtf8(dataFile)
            var loadedFromPrefs = false

            val imagesJson: String?
            val setsJson: String?
            if (!fileJson.isNullOrBlank()) {
                val root = JSONObject(fileJson)
                imagesJson = root.optJSONArray("all_images")?.toString()
                setsJson = root.optJSONArray("image_sets")?.toString()
            } else {
                imagesJson = prefs.getString(KEY_ALL_IMAGES, null)
                setsJson = prefs.getString(KEY_IMAGE_SETS, null)
                loadedFromPrefs = imagesJson != null || setsJson != null
            }

            val newImages = mutableListOf<ImageEntry>()
            if (imagesJson != null) {
                val array = JSONArray(imagesJson)
                for (i in 0 until array.length()) {
                    val obj = array.getJSONObject(i)
                    val uri = Uri.parse(obj.getString("uri"))
                    val isActive = obj.optBoolean("isActive", true)
                    
                    // クロップ済みURIの読み込み（互換性のために残す）
                    val croppedUriStr = obj.optString("croppedUri", "")
                    val croppedUri = if (croppedUriStr.isNotEmpty()) Uri.parse(croppedUriStr) else null
                    
                    // クロップ範囲の読み込み
                    val cropRect = if (obj.has("crop_left")) {
                        RectF(
                            obj.getDouble("crop_left").toFloat(),
                            obj.getDouble("crop_top").toFloat(),
                            obj.getDouble("crop_right").toFloat(),
                            obj.getDouble("crop_bottom").toFloat()
                        )
                    } else null
                    
                    // 紐付けられたチャットIDの読み込み
                    val linkedChatId = if (obj.has("linkedChatId") && !obj.isNull("linkedChatId")) {
                        obj.optString("linkedChatId", null)
                    } else null
                    
                    // 直接説明文の読み込み
                    val description = if (obj.has("description") && !obj.isNull("description")) {
                        obj.optString("description", null)
                    } else null

                    val tags = mutableSetOf<String>()
                    val tagsArray = obj.optJSONArray("tags") ?: JSONArray()
                    for (j in 0 until tagsArray.length()) {
                        tags.add(tagsArray.getString(j))
                    }
                    
                    val entry = ImageEntry(uri, tags, isActive, croppedUri, linkedChatId, cropRect, description)
                    sortEntryTags(context, entry)
                    newImages.add(entry)
                }
            }

            val newSets = mutableListOf<ImageSet>()
            if (setsJson != null) {
                val array = JSONArray(setsJson)
                for (i in 0 until array.length()) {
                    val obj = array.getJSONObject(i)
                    val name = obj.getString("name")
                    
                    // 過去のバージョンのために自動生成かどうかを推測する
                    val isAutoMigrated = obj.optBoolean("isAutoGenerated", 
                        name.contains(" または ") || name.contains("＋") || name.isEmpty()
                    )
                    
                    val usageStr = obj.optString("usage", "BOTH")
                    val usage = try {
                        ImageSetUsage.valueOf(usageStr)
                    } catch (e: Exception) {
                        ImageSetUsage.BOTH
                    }
                    
                    val set = ImageSet(
                        name = name,
                        matchMode = MatchMode.valueOf(obj.optString("matchMode", "ANY")),
                        isActive = obj.optBoolean("isActive", true),
                        isAutoGenerated = isAutoMigrated,
                        usage = usage
                    )
                    val tagsArray = obj.optJSONArray("targetTags") ?: JSONArray()
                    for (j in 0 until tagsArray.length()) {
                        set.targetTags.add(tagsArray.getString(j))
                    }
                    newSets.add(set)
                }
            }

            allImages.clear()
            allImages.addAll(newImages)
            imageSetList.clear()
            imageSetList.addAll(newSets)
            ChatSessionManager.applyImageLinks(context, allImages)
            isLoaded = true
            Log.i("DataManager", "loadData: successfully loaded ${allImages.size} images and ${imageSetList.size} sets.")

            if (loadedFromPrefs) {
                persistToFile(context)
                prefs.edit()
                    .remove(KEY_ALL_IMAGES)
                    .remove(KEY_IMAGE_SETS)
                    .putLong(KEY_REVISION, System.currentTimeMillis())
                    .apply()
            }
        } catch (e: Exception) {
            Log.e("DataManager", "loadData failed!", e)
        } finally {
            isLoading = false
        }
    }

    /**
     * 強制的にロード済みフラグを立てる（バックアップ復元時などに使用）
     */
    @Synchronized
    fun forceSetLoaded() {
        isLoaded = true
    }

    @Synchronized
    fun sortEntryTags(context: Context, entry: ImageEntry) {
        val allTagsOrdered = TagManager.categories.flatMap { it.tags }
        val priorityMap = allTagsOrdered.withIndex().associate { it.value to it.index }
        val sortedList = entry.tags.toList().sortedBy { priorityMap[it] ?: Int.MAX_VALUE }
        entry.tags.clear()
        entry.tags.addAll(sortedList)
    }

    @Synchronized
    fun saveData(context: Context, createBackup: Boolean = true): Boolean {
        if (!isLoaded) {
            Log.e("DataManager", "saveData BLOCKED: Data has not been fully loaded yet. Preventing accidental overwrite!")
            return false
        }

        if (!BackupManager.validateDataIntegrity(context)) {
            if (allImages.isEmpty()) {
                Log.e("DataManager", "saveData blocked by BackupManager due to data integrity failure!")
                BackupManager.restoreLatestAutoBackup(context)
                return false
            }
            Log.w("DataManager", "integrity warning, but in-memory images exist. Saving user edits.")
        }

        try {
            persistToFile(context)
        } catch (e: Exception) {
            Log.e("DataManager", "saveData failed to persist file!", e)
            return false
        }

        val prefs = context.getSharedPreferences(PREFS_NAME, Context.MODE_PRIVATE)
        prefs.edit()
            .remove(KEY_ALL_IMAGES)
            .remove(KEY_IMAGE_SETS)
            .putLong(KEY_REVISION, System.currentTimeMillis())
            .apply()

        if (createBackup) {
            BackupManager.createAutoBackup(context)
        }
        return true
    }

    fun findImageByUri(uriString: String?): ImageEntry? {
        if (uriString.isNullOrBlank()) return null
        return allImages.find { it.uri.toString() == uriString }
    }

    fun getActiveWallpaperImage(context: Context, forChat: Boolean): ImageEntry? {
        val settings = context.getSharedPreferences("settings", Context.MODE_PRIVATE)
        val setName = if (forChat) {
            settings.getString("active_album_name_chat", null)
                ?: settings.getString("active_album_name", null)
        } else {
            settings.getString("active_album_name_homescreen", null)
                ?: settings.getString("active_album_name", null)
        } ?: return null
        val set = imageSetList.find { it.name == setName } ?: return null
        val filtered = set.filterImages(allImages).filter { it.isActive }
        if (filtered.isEmpty()) return null
        val savedIndex = settings.getInt("last_index_for_album_$setName", settings.getInt("active_image_index", 0))
        val index = savedIndex.coerceIn(0, filtered.lastIndex)
        return filtered[index]
    }

    /**
     * 現在ホーム/チャットの壁紙になっている画像が指定リスト内にあればそのURIを返す。
     * AlbumDetail / ImagePreview / FullScreen の3画面でリストの並び順を一致させるために使う。
     */
    fun currentWallpaperUri(context: Context, list: List<ImageEntry>): String? {
        val home = getActiveWallpaperImage(context, false)?.uri?.toString()
        if (home != null && list.any { it.uri.toString() == home }) return home
        val chat = getActiveWallpaperImage(context, true)?.uri?.toString()
        if (chat != null && list.any { it.uri.toString() == chat }) return chat
        return null
    }

    /**
     * 現在壁紙になっている画像をリストの先頭に移動する。
     * 画像一覧(AlbumDetail)・カルーセル(ImagePreview)・全画面(FullScreen)で
     * 同じ並びにするため、どこでもこの関数でピン留めする。
     */
    fun pinCurrentWallpaperFirst(context: Context, list: MutableList<ImageEntry>) {
        val uri = currentWallpaperUri(context, list) ?: return
        val idx = list.indexOfFirst { it.uri.toString() == uri }
        if (idx > 0) {
            val moved = list.removeAt(idx)
            list.add(0, moved)
        }
    }

    private fun dataFile(context: Context): File {
        return File(File(context.filesDir, "app_data").also { if (!it.exists()) it.mkdirs() }, "images_and_sets.json")
    }

    private fun persistToFile(context: Context) {
        val imagesArray = JSONArray()
        allImages.forEach { entry ->
            val obj = JSONObject().apply {
                put("uri", entry.uri.toString())
                put("isActive", entry.isActive)
                
                if (entry.croppedUri != null) {
                    put("croppedUri", entry.croppedUri.toString())
                }
                
                entry.cropRect?.let {
                    put("crop_left", it.left.toDouble())
                    put("crop_top", it.top.toDouble())
                    put("crop_right", it.right.toDouble())
                    put("crop_bottom", it.bottom.toDouble())
                }
                
                // 紐付けられたチャットIDの保存
                if (entry.linkedChatId != null) {
                    put("linkedChatId", entry.linkedChatId)
                }
                
                // 直接説明文の保存
                if (entry.description != null) {
                    put("description", entry.description)
                }

                sortEntryTags(context, entry)

                val tagsArray = JSONArray()
                entry.tags.forEach { tagsArray.put(it) }
                put("tags", tagsArray)
            }
            imagesArray.put(obj)
        }

        val setsArray = JSONArray()
        imageSetList.forEach { set ->
            val obj = JSONObject().apply {
                put("name", set.name)
                put("matchMode", set.matchMode.name)
                put("isActive", set.isActive)
                put("isAutoGenerated", set.isAutoGenerated)
                put("usage", set.usage.name)
                val targetTagsArray = JSONArray()
                set.targetTags.forEach { targetTagsArray.put(it) }
                put("targetTags", targetTagsArray)
            }
            setsArray.put(obj)
        }

        val root = JSONObject().apply {
            put("all_images", imagesArray)
            put("image_sets", setsArray)
        }
        AtomicFiles.writeUtf8(dataFile(context), root.toString())
    }

    @Synchronized
    fun sortImagesByTagPriority(context: Context) {
        val allTagsOrdered = TagManager.categories.flatMap { it.tags }
        val priorityMap = allTagsOrdered.withIndex().associate { it.value to it.index }
        allImages.forEach { sortEntryTags(context, it) }

        val settingsPrefs = context.getSharedPreferences("settings", Context.MODE_PRIVATE)
        val sortByPriorityFirst = settingsPrefs.getBoolean("sort_by_priority_first", true)

        if (sortByPriorityFirst) {
            allImages.sortWith(compareBy<ImageEntry> { entry ->
                    entry.tags.mapNotNull { priorityMap[it] }.minOrNull() ?: Int.MAX_VALUE
                }.thenByDescending { it.tags.size }
            )
        } else {
            allImages.sortWith(compareByDescending<ImageEntry> { it.tags.size }
                .thenBy { entry ->
                    entry.tags.mapNotNull { priorityMap[it] }.minOrNull() ?: Int.MAX_VALUE
                }
            )
        }
        saveData(context)
    }

    fun getFilteredImages(setName: String): List<ImageEntry> {
        val set = imageSetList.find { it.name == setName } ?: return emptyList()
        return set.filterImages(allImages)
    }

    /**
     * 画像ファイル本体を削除する。
     *
     * SAF文書URI（生成画像の保存先）・MediaStore・file:// の各形式に応じて
     * 複数の方法で削除を試み、どの方法でも「削除できた」と言われなかった場合でも、
     * 実際にファイルが存在しなくなっていれば削除成功とみなす（冪等）。
     */
    fun deleteImageFile(context: Context, uri: Uri): Boolean {
        val scheme = uri.scheme?.lowercase() ?: ""
        return try {
            when (scheme) {
                "file" -> deleteLocalFile(uri)
                "content" -> deleteContentUri(context, uri)
                else -> false
            }
        } catch (e: Exception) {
            Log.e("DataManager", "deleteImageFile failed for $uri", e)
            false
        }
    }

    /**
     * 画像エントリの本体ファイルと、紐づくサムネイルファイルをまとめて削除する。
     * 本体を消せたかどうかを戻り値とする（サムネイルは本体の結果に影響させない）。
     */
    fun deleteImageEntryFiles(context: Context, entry: ImageEntry): Boolean {
        val mainDeleted = deleteImageFile(context, entry.uri)
        val thumbUri = entry.thumbnailUri
        if (thumbUri != null &&
            thumbUri.toString() != entry.uri.toString() &&
            !ImageStoragePolicy.isRemote(thumbUri)
        ) {
            try {
                deleteImageFile(context, thumbUri)
            } catch (e: Exception) {
                Log.e("DataManager", "Failed to delete thumbnail: $thumbUri", e)
            }
        }
        return mainDeleted
    }

    /** file:// の実体をFile APIで直接消す。既に無ければ削除済みとして成功扱い。 */
    private fun deleteLocalFile(uri: Uri): Boolean {
        val path = uri.path ?: return false
        val file = File(path)
        if (!file.exists()) return true
        return try {
            file.delete() || !file.exists()
        } catch (e: Exception) {
            Log.e("DataManager", "Failed to delete file directly: $path", e)
            false
        }
    }

    /** content:// を、文書URIならSAF経由、それ以外はContentResolver経由で消す。 */
    private fun deleteContentUri(context: Context, uri: Uri): Boolean {
        val isDocument = try {
            DocumentsContract.isDocumentUri(context, uri)
        } catch (e: Exception) {
            false
        }

        if (isDocument) {
            if (deleteViaDocumentsContract(context, uri)) return true
            if (deleteViaDocumentFile(context, uri)) return true
        } else {
            // MediaStore などの一般プロバイダ
            if (deleteViaContentResolver(context, uri)) return true
            if (deleteViaDocumentsContract(context, uri)) return true
            if (deleteViaDocumentFile(context, uri)) return true
        }

        // すべての方法が失敗と報告しても、実際には消えている場合がある（プロバイダの仕様差）。
        // 存在確認して本当に無ければ削除成功とみなす。
        return !contentUriStillExists(context, uri)
    }

    private fun deleteViaDocumentsContract(context: Context, uri: Uri): Boolean {
        return try {
            DocumentsContract.deleteDocument(context.contentResolver, uri)
        } catch (e: Exception) {
            Log.e("DataManager", "deleteDocument failed for $uri: ${e.message}")
            false
        }
    }

    private fun deleteViaDocumentFile(context: Context, uri: Uri): Boolean {
        return try {
            val document = DocumentFile.fromSingleUri(context, uri) ?: return false
            if (!document.exists()) true else document.delete()
        } catch (e: Exception) {
            Log.e("DataManager", "DocumentFile delete failed for $uri: ${e.message}")
            false
        }
    }

    private fun deleteViaContentResolver(context: Context, uri: Uri): Boolean {
        return try {
            context.contentResolver.delete(uri, null, null) > 0
        } catch (e: Exception) {
            Log.e("DataManager", "ContentResolver delete failed for $uri: ${e.message}")
            false
        }
    }

    /** content:// の実体がまだ残っているかどうか。判定不能なら「残っている」扱い。 */
    private fun contentUriStillExists(context: Context, uri: Uri): Boolean {
        return try {
            if (DocumentsContract.isDocumentUri(context, uri)) {
                DocumentFile.fromSingleUri(context, uri)?.exists() ?: true
            } else {
                try {
                    context.contentResolver.openInputStream(uri)?.use { }
                    true
                } catch (e: FileNotFoundException) {
                    false
                } catch (e: Exception) {
                    true
                }
            }
        } catch (e: Exception) {
            true
        }
    }
}