package com.example.kennys_dokidoki_wallpaper

import android.content.Context
import android.graphics.RectF
import android.net.Uri
import android.provider.DocumentsContract
import android.util.Log
import org.json.JSONArray
import org.json.JSONObject
import java.io.File

object DataManager {
    private const val PREFS_NAME = "wallpaper_prefs"
    private const val KEY_ALL_IMAGES = "all_images"
    private const val KEY_IMAGE_SETS = "image_sets"

    val allImages = mutableListOf<ImageEntry>()
    val imageSetList = mutableListOf<ImageSet>()

    @Volatile
    var isLoaded = false
        private set

    @Volatile
    private var isLoading = false

    @Synchronized
    fun loadData(context: Context) {
        if (isLoading) {
            Log.d("DataManager", "loadData: already loading, skip.")
            return
        }
        isLoading = true
        try {
            val prefs = context.getSharedPreferences(PREFS_NAME, Context.MODE_PRIVATE)
            
            val imagesJson = prefs.getString(KEY_ALL_IMAGES, null)
            allImages.clear()
            if (imagesJson != null) {
                val array = JSONArray(imagesJson)
                for (i in 0 until array.length()) {
                    val obj = array.getJSONObject(i)
                    val uri = Uri.parse(obj.getString("uri"))
                    val isActive = obj.optBoolean("isActive", true)
                    
                    // クロップ済みURIの読み込み（互換性のために残す）
                    val croppedUriStr = obj.optString("croppedUri", "")
                    val croppedUri = if (croppedUriStr.isNotEmpty()) Uri.parse(croppedUriStr) else null
                    
                    // クロップ範囲の読み込み
                    val cropRect = if (obj.has("crop_left")) {
                        RectF(
                            obj.getDouble("crop_left").toFloat(),
                            obj.getDouble("crop_top").toFloat(),
                            obj.getDouble("crop_right").toFloat(),
                            obj.getDouble("crop_bottom").toFloat()
                        )
                    } else null
                    
                    // 紐付けられたチャットIDの読み込み
                    val linkedChatId = if (obj.has("linkedChatId")) obj.getString("linkedChatId") else null
                    
                    // 直接説明文の読み込み
                    val description = if (obj.has("description")) obj.getString("description") else null

                    val tags = mutableSetOf<String>()
                    val tagsArray = obj.optJSONArray("tags") ?: JSONArray()
                    for (j in 0 until tagsArray.length()) {
                        tags.add(tagsArray.getString(j))
                    }
                    
                    val entry = ImageEntry(uri, tags, isActive, croppedUri, linkedChatId, cropRect, description)
                    sortEntryTags(context, entry)
                    allImages.add(entry)
                }
            }

            val setsJson = prefs.getString(KEY_IMAGE_SETS, null)
            imageSetList.clear()
            if (setsJson != null) {
                val array = JSONArray(setsJson)
                for (i in 0 until array.length()) {
                    val obj = array.getJSONObject(i)
                    val name = obj.getString("name")
                    
                    // 過去のバージョンのために自動生成かどうかを推測する
                    val isAutoMigrated = obj.optBoolean("isAutoGenerated", 
                        name.contains(" または ") || name.contains("＋") || name.isEmpty()
                    )
                    
                    val usageStr = obj.optString("usage", "BOTH")
                    val usage = try {
                        ImageSetUsage.valueOf(usageStr)
                    } catch (e: Exception) {
                        ImageSetUsage.BOTH
                    }
                    
                    val set = ImageSet(
                        name = name,
                        matchMode = MatchMode.valueOf(obj.optString("matchMode", "ANY")),
                        isActive = obj.optBoolean("isActive", true),
                        isAutoGenerated = isAutoMigrated,
                        usage = usage
                    )
                    val tagsArray = obj.optJSONArray("targetTags") ?: JSONArray()
                    for (j in 0 until tagsArray.length()) {
                        set.targetTags.add(tagsArray.getString(j))
                    }
                    imageSetList.add(set)
                }
            }
            isLoaded = true
            Log.i("DataManager", "loadData: successfully loaded ${allImages.size} images and ${imageSetList.size} sets.")
        } catch (e: Exception) {
            Log.e("DataManager", "loadData failed!", e)
        } finally {
            isLoading = false
        }
    }

    /**
     * 強制的にロード済みフラグを立てる（バックアップ復元時などに使用）
     */
    @Synchronized
    fun forceSetLoaded() {
        isLoaded = true
    }

    @Synchronized
    fun sortEntryTags(context: Context, entry: ImageEntry) {
        val allTagsOrdered = TagManager.categories.flatMap { it.tags }
        val priorityMap = allTagsOrdered.withIndex().associate { it.value to it.index }
        val sortedList = entry.tags.toList().sortedBy { priorityMap[it] ?: Int.MAX_VALUE }
        entry.tags.clear()
        entry.tags.addAll(sortedList)
    }

    @Synchronized
    fun saveData(context: Context) {
        if (!isLoaded) {
            Log.e("DataManager", "saveData BLOCKED: Data has not been fully loaded yet. Preventing accidental overwrite!")
            return
        }

        if (!BackupManager.validateDataIntegrity(context)) {
            Log.e("DataManager", "saveData blocked by BackupManager due to data integrity failure!")
            BackupManager.restoreLatestAutoBackup(context)
            return
        }

        val prefs = context.getSharedPreferences(PREFS_NAME, Context.MODE_PRIVATE)
        
        val imagesArray = JSONArray()
        allImages.forEach { entry ->
            val obj = JSONObject().apply {
                put("uri", entry.uri.toString())
                put("isActive", entry.isActive)
                
                if (entry.croppedUri != null) {
                    put("croppedUri", entry.croppedUri.toString())
                }
                
                entry.cropRect?.let {
                    put("crop_left", it.left.toDouble())
                    put("crop_top", it.top.toDouble())
                    put("crop_right", it.right.toDouble())
                    put("crop_bottom", it.bottom.toDouble())
                }
                
                // 紐付けられたチャットIDの保存
                if (entry.linkedChatId != null) {
                    put("linkedChatId", entry.linkedChatId)
                }
                
                // 直接説明文の保存
                if (entry.description != null) {
                    put("description", entry.description)
                }

                sortEntryTags(context, entry)

                val tagsArray = JSONArray()
                entry.tags.forEach { tagsArray.put(it) }
                put("tags", tagsArray)
            }
            imagesArray.put(obj)
        }

        val setsArray = JSONArray()
        imageSetList.forEach { set ->
            val obj = JSONObject().apply {
                put("name", set.name)
                put("matchMode", set.matchMode.name)
                put("isActive", set.isActive)
                put("isAutoGenerated", set.isAutoGenerated)
                put("usage", set.usage.name)
                val targetTagsArray = JSONArray()
                set.targetTags.forEach { targetTagsArray.put(it) }
                put("targetTags", targetTagsArray)
            }
            setsArray.put(obj)
        }
        
        prefs.edit().apply {
            putString(KEY_ALL_IMAGES, imagesArray.toString())
            putString(KEY_IMAGE_SETS, setsArray.toString())
            apply()
        }

        // セーブ成功後、自動バックアップを作成
        BackupManager.createAutoBackup(context)
    }

    @Synchronized
    fun sortImagesByTagPriority(context: Context) {
        val allTagsOrdered = TagManager.categories.flatMap { it.tags }
        val priorityMap = allTagsOrdered.withIndex().associate { it.value to it.index }
        allImages.forEach { sortEntryTags(context, it) }

        val settingsPrefs = context.getSharedPreferences("settings", Context.MODE_PRIVATE)
        val sortByPriorityFirst = settingsPrefs.getBoolean("sort_by_priority_first", true)

        if (sortByPriorityFirst) {
            allImages.sortWith(compareBy<ImageEntry> { entry ->
                    entry.tags.mapNotNull { priorityMap[it] }.minOrNull() ?: Int.MAX_VALUE
                }.thenByDescending { it.tags.size }
            )
        } else {
            allImages.sortWith(compareByDescending<ImageEntry> { it.tags.size }
                .thenBy { entry ->
                    entry.tags.mapNotNull { priorityMap[it] }.minOrNull() ?: Int.MAX_VALUE
                }
            )
        }
        saveData(context)
    }

    fun getFilteredImages(setName: String): List<ImageEntry> {
        val set = imageSetList.find { it.name == setName } ?: return emptyList()
        return set.filterImages(allImages)
    }

    fun deleteImageFile(context: Context, uri: Uri): Boolean {
        var deleted = false
        try {
            if (DocumentsContract.isDocumentUri(context, uri)) {
                deleted = DocumentsContract.deleteDocument(context.contentResolver, uri)
            } else {
                val rowsDeleted = context.contentResolver.delete(uri, null, null)
                deleted = rowsDeleted > 0
            }
        } catch (e: Exception) {
            Log.e("DataManager", "Failed to delete via ContentResolver", e)
        }
        
        if (!deleted && uri.scheme == "file") {
            try {
                val file = File(uri.path ?: "")
                if (file.exists()) {
                    deleted = file.delete()
                }
            } catch (e: Exception) {
                Log.e("DataManager", "Failed to delete file directly", e)
            }
        }
        return deleted
    }
}