package com.example.kennys_dokidoki_wallpaper

enum class MatchMode {
    ANY, // いずれか一つでもタグが一致すればOK
    ALL  // すべてのタグが一致しなければならない
}

enum class ImageSetUsage {
    HOMESCREEN,
    CHAT,
    BOTH
}

data class ImageSet(
    var name: String,
    val targetTags: MutableSet<String> = mutableSetOf(),
    var matchMode: MatchMode = MatchMode.ANY,
    var isActive: Boolean = true,
    var isAutoGenerated: Boolean = false,
    var usage: ImageSetUsage = ImageSetUsage.BOTH
) {
    /**
     * 指定されたタグのセットが、このイメージセットの条件に一致するか判定する。
     */
    fun isMatch(imageTags: Set<String>): Boolean {
        if (targetTags.isEmpty()) return false
        
        // 「自動的に持つタグ」も含めて判定を行うわ
        val effectiveTags = TagManager.getEffectiveTags(imageTags)
        
        return when (matchMode) {
            MatchMode.ANY -> targetTags.any { it in effectiveTags }
            MatchMode.ALL -> effectiveTags.containsAll(targetTags)
        }
    }

    /**
     * 全画像の中から、このセットの条件に合う画像エントリを抽出する。
     */
    fun filterImages(allImages: List<ImageEntry>): List<ImageEntry> {
        return allImages.filter { isMatch(it.tags) }
    }
}